[target.wasm32-unknown-unknown]
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "link-arg=--initial-memory=2097152",
    "-C", "link-arg=--stack-first",
    "-C", "link-arg=--export-table",
]

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]
