# Network Configuration for CosmWasm Tontine Contract
# This file contains configuration parameters for different networks

[testnet]
chain_id = "safro-testnet-1"
rpc_url = "https://rpc.testnet.safrochain.com"
api_url = "https://rest.testnet.safrochain.com"
gas_prices = "0.025usaf"
gas_adjustment = 1.5
account_prefix = "addr_safro"
denom = "usaf"
block_time = 6

# Contract configuration templates
[contract.default]
contribution_amount = "1000000"  # 1 SAF in usaf
round_frequency = 86400          # 1 day in seconds
late_penalty = "50000"           # 0.05 SAF in usaf
protocol_fees = "10000"          # 0.01 SAF in usaf
time_guards = 3600               # 1 hour in seconds

[contract.small]
contribution_amount = "100000"   # 0.1 SAF in usaf
round_frequency = 604800         # 1 week in seconds
late_penalty = "5000"            # 0.005 SAF in usaf
protocol_fees = "1000"           # 0.001 SAF in usaf
time_guards = 7200               # 2 hours in seconds

[contract.large]
contribution_amount = "10000000" # 10 SAF in usaf
round_frequency = 2592000        # 30 days in seconds
late_penalty = "500000"          # 0.5 SAF in usaf
protocol_fees = "100000"         # 0.1 SAF in usaf
time_guards = 1800               # 30 minutes in seconds

# Development configuration
[development]
auto_start = false
debug_mode = true
log_level = "debug"
max_members = 100
max_rounds = 50
max_beneficiaries = 50

# Production configuration
[production]
auto_start = false
debug_mode = false
log_level = "info"
max_members = 1000
max_rounds = 500
max_beneficiaries = 500

# Security configuration
[security]
max_contribution_amount = "100000000"  # 100 SAF in usaf
min_contribution_amount = "1000"       # 0.001 SAF in usaf
max_round_frequency = 31536000         # 1 year in seconds
min_round_frequency = 3600             # 1 hour in seconds
max_late_penalty = "1000000"           # 1 SAF in usaf
max_protocol_fees = "100000"           # 0.1 SAF in usaf
max_time_guards = 86400                # 1 day in seconds
min_time_guards = 300                  # 5 minutes in seconds

# Fee structure
[fees]
protocol_fee_percentage = 0.01         # 1% of contribution
late_penalty_percentage = 0.05         # 5% of contribution
arbitration_fee = "1000"               # 0.001 SAF in usaf
dispute_resolution_fee = "5000"        # 0.005 SAF in usaf

# Timeouts and limits
[timeouts]
member_registration_timeout = 300      # 5 minutes
contribution_timeout = 86400           # 1 day
distribution_timeout = 3600            # 1 hour
dispute_resolution_timeout = 604800    # 1 week
penalty_payment_timeout = 2592000      # 30 days

# Network-specific overrides
[networks.cosmoshub]
chain_id = "cosmoshub-4"
rpc_url = "https://rpc.cosmos.network"
api_url = "https://api.cosmos.network"
gas_prices = "0.025uatom"
denom = "uatom"

[networks.osmosis]
chain_id = "osmosis-1"
rpc_url = "https://rpc.osmosis.zone"
api_url = "https://api.osmosis.zone"
gas_prices = "0.0025uosmo"
denom = "uosmo"

[networks.juno]
chain_id = "juno-1"
rpc_url = "https://rpc.juno.strange.love"
api_url = "https://api.juno.strange.love"
gas_prices = "0.0025ujuno"
denom = "ujuno"
